---
- name: Install HAProxy
  package:
    name: haproxy
    state: latest

- name: Enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Configure HAProxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy